-- 下订单超过4次的女顾客
SELECT o.CUSTOMER_ID,COUNT(o.CUSTOMER_ID) as orders_ct FROM OE.ORDERS o,OE.CUSTOMERS c
WHERE o.CUSTOMER_ID=c.CUSTOMER_ID
  AND c.GENDER='F'
GROUP BY o.CUSTOMER_ID
HAVING COUNT(o.CUSTOMER_ID)>4
ORDER BY orders_ct,o.CUSTOMER_ID;
