-- 下订单超过4次的女顾客
SELECT c.CUSTOMER_ID,COUNT(o.ORDER_ID) as orders_ct
  FROM OE.CUSTOMERS c
  JOIN OE.ORDERS o
  ON c.CUSTOMER_ID=o.CUSTOMER_ID
  GROUP BY c.CUSTOMER_ID
  HAVING COUNT(o.ORDER_ID) > 4
  ORDER BY orders_ct, c.CUSTOMER_ID