version: '3'
services:
  oracle-xe-11g:
    privileged: true
    image: terwer/oracle-xe-11g:latest
    container_name: oracle-xe-11g
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "1521:1521"
    environment:
      - processes=200
      - DATABASES=sample
    volumes:
      - .oracle_data:/u01/app/oracle